spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Microservices
  application:
    name: RATINGS-SERVICE
server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka